/* 
DO NOT EDIT This file is generated DO NOT EDIT
*/
#ifndef COOL_TYPES_H
#define COOL_TYPES_H
#include <stdlib.h>
#include <stdio.h>

typedef struct CoolType CoolType;

typedef struct CoolTypeOps {
  CoolId       (* id    )( CoolType t );
  const char * (* name  )( CoolType t );
  int        * (* cmp   )( CoolType a, CoolType b );
  int        * (* ident )( CoolType a, CoolType b );
  uint32_t   * (* hash  )( CoolType t);
} CoolTypeOps;

struct CoolType {
  void        * obj;
  CoolTypeOps * ops;
};

/*
 This function takes a void pointer, the caller is expected to imlement this
 fuciton internally ie cast the obj to a known type, test if this is the
 required item etc. If this is the object return true else return false.
*/
typedef int (*CoolIdent )(void * obj, void * item);
typedef int (*CoolCompare )(void * a, void * b);

typedef enum CoolId {
  CoolNill = 0,
  CoolAST = 1,
  CoolAtom = 2,
  CoolAVL = 3,
  CoolArena = 4,
  CoolBTree = 5,
  CoolBinTree = 6,
  CoolBitMap = 7,
  CoolBoolean = 8,
  CoolByte = 9,
  CoolChar = 10,
  CoolClass = 11,
  CoolClosure = 12,
  CoolComplex = 13,
  CoolConst = 14,
  CoolContainer = 15,
  CoolDopeVector = 16,
  CoolDouble = 17,
  CoolEnum = 18,
  CoolError = 19,
  CoolFloat = 20,
  CoolFunction = 21,
  CoolGraph = 22,
  CoolHash = 23,
  CoolHeap = 24,
  CoolInstance = 25,
  CoolInteger = 26,
  CoolList = 27,
  CoolMatrix = 28,
  CoolMultiMap = 29,
  CoolMultiSet = 30,
  CoolNode = 31,
  CoolObject = 32,
  CoolPointer = 33,
  CoolPool = 34,
  CoolQueue = 35,
  CoolRBTree = 36,
  CoolRing = 37,
  CoolSExp = 38,
  CoolSet = 39,
  CoolStack = 40,
  CoolStream = 41,
  CoolString = 42,
  CoolStruct = 43,
  CoolSuffixArray = 44,
  CoolSuffixTree = 45,
  CoolSymTable = 46,
  CoolTrie = 47,
  CoolTuple = 48,
  CoolUnion = 49,
  CoolVector = 50,
  CoolVoid = 51,
} CoolId;

typedef struct CoolTypes {
  CoolId       Nill;
  CoolId       AST;
  CoolId       Atom;
  CoolId       AVL;
  CoolId       Arena;
  CoolId       BTree;
  CoolId       BinTree;
  CoolId       BitMap;
  CoolId       Boolean;
  CoolId       Byte;
  CoolId       Char;
  CoolId       Class;
  CoolId       Closure;
  CoolId       Complex;
  CoolId       Const;
  CoolId       Container;
  CoolId       DopeVector;
  CoolId       Double;
  CoolId       Enum;
  CoolId       Error;
  CoolId       Float;
  CoolId       Function;
  CoolId       Graph;
  CoolId       Hash;
  CoolId       Heap;
  CoolId       Instance;
  CoolId       Integer;
  CoolId       List;
  CoolId       Matrix;
  CoolId       MultiMap;
  CoolId       MultiSet;
  CoolId       Node;
  CoolId       Object;
  CoolId       Pointer;
  CoolId       Pool;
  CoolId       Queue;
  CoolId       RBTree;
  CoolId       Ring;
  CoolId       SExp;
  CoolId       Set;
  CoolId       Stack;
  CoolId       Stream;
  CoolId       String;
  CoolId       Struct;
  CoolId       SuffixArray;
  CoolId       SuffixTree;
  CoolId       SymTable;
  CoolId       Trie;
  CoolId       Tuple;
  CoolId       Union;
  CoolId       Vector;
  CoolId       Void;
} CoolTypes;

const static CoolTypes CoolTypeTable = {
  Nill,
  AST,
  Atom,
  AVL,
  Arena,
  BTree,
  BinTree,
  BitMap,
  Boolean,
  Byte,
  Char,
  Class,
  Closure,
  Complex,
  Const,
  Container,
  DopeVector,
  Double,
  Enum,
  Error,
  Float,
  Function,
  Graph,
  Hash,
  Heap,
  Instance,
  Integer,
  List,
  Matrix,
  MultiMap,
  MultiSet,
  Node,
  Object,
  Pointer,
  Pool,
  Queue,
  RBTree,
  Ring,
  SExp,
  Set,
  Stack,
  Stream,
  String,
  Struct,
  SuffixArray,
  SuffixTree,
  SymTable,
  Trie,
  Tuple,
  Union,
  Vector,
  Void,
};

static struct Cool_Func_Table CFT[] = {
  { 0, "CoolNill", NULL, NULL /* &cool_nill_new, &cool_nill_delete */ },
  { 1, "CoolAST", NULL, NULL /* &cool_ast_new, &cool_ast_delete */ },
  { 2, "CoolAtom", NULL, NULL /* &cool_atom_new, &cool_atom_delete */ },
  { 3, "CoolAVL", NULL, NULL /* &cool_avl_new, &cool_avl_delete */ },
  { 4, "CoolArena", NULL, NULL /* &cool_arena_new, &cool_arena_delete */ },
  { 5, "CoolBTree", NULL, NULL /* &cool_btree_new, &cool_btree_delete */ },
  { 6, "CoolBinTree", NULL, NULL /* &cool_bintree_new, &cool_bintree_delete */ },
  { 7, "CoolBitMap", NULL, NULL /* &cool_bitmap_new, &cool_bitmap_delete */ },
  { 8, "CoolBoolean", NULL, NULL /* &cool_boolean_new, &cool_boolean_delete */ },
  { 9, "CoolByte", NULL, NULL /* &cool_byte_new, &cool_byte_delete */ },
  { 10, "CoolChar", NULL, NULL /* &cool_char_new, &cool_char_delete */ },
  { 11, "CoolClass", NULL, NULL /* &cool_class_new, &cool_class_delete */ },
  { 12, "CoolClosure", NULL, NULL /* &cool_closure_new, &cool_closure_delete */ },
  { 13, "CoolComplex", NULL, NULL /* &cool_complex_new, &cool_complex_delete */ },
  { 14, "CoolConst", NULL, NULL /* &cool_const_new, &cool_const_delete */ },
  { 15, "CoolContainer", NULL, NULL /* &cool_container_new, &cool_container_delete */ },
  { 16, "CoolDopeVector", NULL, NULL /* &cool_dopevector_new, &cool_dopevector_delete */ },
  { 17, "CoolDouble", NULL, NULL /* &cool_double_new, &cool_double_delete */ },
  { 18, "CoolEnum", NULL, NULL /* &cool_enum_new, &cool_enum_delete */ },
  { 19, "CoolError", NULL, NULL /* &cool_error_new, &cool_error_delete */ },
  { 20, "CoolFloat", NULL, NULL /* &cool_float_new, &cool_float_delete */ },
  { 21, "CoolFunction", NULL, NULL /* &cool_function_new, &cool_function_delete */ },
  { 22, "CoolGraph", NULL, NULL /* &cool_graph_new, &cool_graph_delete */ },
  { 23, "CoolHash", NULL, NULL /* &cool_hash_new, &cool_hash_delete */ },
  { 24, "CoolHeap", NULL, NULL /* &cool_heap_new, &cool_heap_delete */ },
  { 25, "CoolInstance", NULL, NULL /* &cool_instance_new, &cool_instance_delete */ },
  { 26, "CoolInteger", NULL, NULL /* &cool_integer_new, &cool_integer_delete */ },
  { 27, "CoolList", NULL, NULL /* &cool_list_new, &cool_list_delete */ },
  { 28, "CoolMatrix", NULL, NULL /* &cool_matrix_new, &cool_matrix_delete */ },
  { 29, "CoolMultiMap", NULL, NULL /* &cool_multimap_new, &cool_multimap_delete */ },
  { 30, "CoolMultiSet", NULL, NULL /* &cool_multiset_new, &cool_multiset_delete */ },
  { 31, "CoolNode", NULL, NULL /* &cool_node_new, &cool_node_delete */ },
  { 32, "CoolObject", NULL, NULL /* &cool_object_new, &cool_object_delete */ },
  { 33, "CoolPointer", NULL, NULL /* &cool_pointer_new, &cool_pointer_delete */ },
  { 34, "CoolPool", NULL, NULL /* &cool_pool_new, &cool_pool_delete */ },
  { 35, "CoolQueue", NULL, NULL /* &cool_queue_new, &cool_queue_delete */ },
  { 36, "CoolRBTree", NULL, NULL /* &cool_rbtree_new, &cool_rbtree_delete */ },
  { 37, "CoolRing", NULL, NULL /* &cool_ring_new, &cool_ring_delete */ },
  { 38, "CoolSExp", NULL, NULL /* &cool_sexp_new, &cool_sexp_delete */ },
  { 39, "CoolSet", NULL, NULL /* &cool_set_new, &cool_set_delete */ },
  { 40, "CoolStack", NULL, NULL /* &cool_stack_new, &cool_stack_delete */ },
  { 41, "CoolStream", NULL, NULL /* &cool_stream_new, &cool_stream_delete */ },
  { 42, "CoolString", NULL, NULL /* &cool_string_new, &cool_string_delete */ },
  { 43, "CoolStruct", NULL, NULL /* &cool_struct_new, &cool_struct_delete */ },
  { 44, "CoolSuffixArray", NULL, NULL /* &cool_suffixarray_new, &cool_suffixarray_delete */ },
  { 45, "CoolSuffixTree", NULL, NULL /* &cool_suffixtree_new, &cool_suffixtree_delete */ },
  { 46, "CoolSymTable", NULL, NULL /* &cool_symtable_new, &cool_symtable_delete */ },
  { 47, "CoolTrie", NULL, NULL /* &cool_trie_new, &cool_trie_delete */ },
  { 48, "CoolTuple", NULL, NULL /* &cool_tuple_new, &cool_tuple_delete */ },
  { 49, "CoolUnion", NULL, NULL /* &cool_union_new, &cool_union_delete */ },
  { 50, "CoolVector", NULL, NULL /* &cool_vector_new, &cool_vector_delete */ },
  { 51, "CoolVoid", NULL, NULL /* &cool_void_new, &cool_void_delete */ },
}; 


#endif /* COOL_TYPES_H */

