COOL_TYPE_DEF(Nill, 0,"Nill",Nill_T,Nill_REF,Nill_SYM)
COOL_TYPE_DEF(AST, 1,"AST",AST_T,AST_REF,AST_SYM)
COOL_TYPE_DEF(Atom, 2,"Atom",Atom_T,Atom_REF,Atom_SYM)
COOL_TYPE_DEF(AVL, 3,"AVL",AVL_T,AVL_REF,AVL_SYM)
COOL_TYPE_DEF(Arena, 4,"Arena",Arena_T,Arena_REF,Arena_SYM)
COOL_TYPE_DEF(BTree, 5,"BTree",BTree_T,BTree_REF,BTree_SYM)
COOL_TYPE_DEF(BinTree, 6,"BinTree",BinTree_T,BinTree_REF,BinTree_SYM)
COOL_TYPE_DEF(BitMap, 7,"BitMap",BitMap_T,BitMap_REF,BitMap_SYM)
COOL_TYPE_DEF(Boolean, 8,"Boolean",Boolean_T,Boolean_REF,Boolean_SYM)
COOL_TYPE_DEF(Byte, 9,"Byte",Byte_T,Byte_REF,Byte_SYM)
COOL_TYPE_DEF(Char, 10,"Char",Char_T,Char_REF,Char_SYM)
COOL_TYPE_DEF(Class, 11,"Class",Class_T,Class_REF,Class_SYM)
COOL_TYPE_DEF(Closure, 12,"Closure",Closure_T,Closure_REF,Closure_SYM)
COOL_TYPE_DEF(Complex, 13,"Complex",Complex_T,Complex_REF,Complex_SYM)
COOL_TYPE_DEF(Const, 14,"Const",Const_T,Const_REF,Const_SYM)
COOL_TYPE_DEF(Container, 15,"Container",Container_T,Container_REF,Container_SYM)
COOL_TYPE_DEF(DopeVector, 16,"DopeVector",DopeVector_T,DopeVector_REF,DopeVector_SYM)
COOL_TYPE_DEF(Double, 17,"Double",Double_T,Double_REF,Double_SYM)
COOL_TYPE_DEF(Enum, 18,"Enum",Enum_T,Enum_REF,Enum_SYM)
COOL_TYPE_DEF(Error, 19,"Error",Error_T,Error_REF,Error_SYM)
COOL_TYPE_DEF(Float, 20,"Float",Float_T,Float_REF,Float_SYM)
COOL_TYPE_DEF(Function, 21,"Function",Function_T,Function_REF,Function_SYM)
COOL_TYPE_DEF(Graph, 22,"Graph",Graph_T,Graph_REF,Graph_SYM)
COOL_TYPE_DEF(Hash, 23,"Hash",Hash_T,Hash_REF,Hash_SYM)
COOL_TYPE_DEF(Heap, 24,"Heap",Heap_T,Heap_REF,Heap_SYM)
COOL_TYPE_DEF(Instance, 25,"Instance",Instance_T,Instance_REF,Instance_SYM)
COOL_TYPE_DEF(Integer, 26,"Integer",Integer_T,Integer_REF,Integer_SYM)
COOL_TYPE_DEF(List, 27,"List",List_T,List_REF,List_SYM)
COOL_TYPE_DEF(Matrix, 28,"Matrix",Matrix_T,Matrix_REF,Matrix_SYM)
COOL_TYPE_DEF(MultiMap, 29,"MultiMap",MultiMap_T,MultiMap_REF,MultiMap_SYM)
COOL_TYPE_DEF(MultiSet, 30,"MultiSet",MultiSet_T,MultiSet_REF,MultiSet_SYM)
COOL_TYPE_DEF(Node, 31,"Node",Node_T,Node_REF,Node_SYM)
COOL_TYPE_DEF(Object, 32,"Object",Object_T,Object_REF,Object_SYM)
COOL_TYPE_DEF(Pointer, 33,"Pointer",Pointer_T,Pointer_REF,Pointer_SYM)
COOL_TYPE_DEF(Pool, 34,"Pool",Pool_T,Pool_REF,Pool_SYM)
COOL_TYPE_DEF(Queue, 35,"Queue",Queue_T,Queue_REF,Queue_SYM)
COOL_TYPE_DEF(RBTree, 36,"RBTree",RBTree_T,RBTree_REF,RBTree_SYM)
COOL_TYPE_DEF(Ring, 37,"Ring",Ring_T,Ring_REF,Ring_SYM)
COOL_TYPE_DEF(SExp, 38,"SExp",SExp_T,SExp_REF,SExp_SYM)
COOL_TYPE_DEF(Set, 39,"Set",Set_T,Set_REF,Set_SYM)
COOL_TYPE_DEF(Stack      , 40,"Stack",Stack_T,Stack_REF,Stack_SYM)
COOL_TYPE_DEF(Stream     , 41,"Stream",Stream_T,Stream_REF,Stream_SYM)
COOL_TYPE_DEF(String     , 42,"String",String_T,String_REF,String_SYM)
COOL_TYPE_DEF(Struct     , 43,"Struct",Struct_T,Struct_REF,Struct_SYM)
COOL_TYPE_DEF(SuffixArray, 44,"SuffixArray",SuffixArray_T,SuffixArray_REF,SuffixArray_SYM)
COOL_TYPE_DEF(SuffixTree , 45,"SuffixTree",SuffixTree_T,SuffixTree_REF,SuffixTree_SYM)
COOL_TYPE_DEF(SymTable   , 46,"SymTable",SymTable_T,SymTable_REF,SymTable_SYM)
COOL_TYPE_DEF(Trie       , 47,"Trie",Trie_T,Trie_REF,Trie_SYM)
COOL_TYPE_DEF(Tuple      , 48,"Tuple",Tuple_T,Tuple_REF,Tuple_SYM)
COOL_TYPE_DEF(Union      , 49,"Union",Union_T,Union_REF,Union_SYM)
COOL_TYPE_DEF(Vector     , 50,"Vector",Vector_T,Vector_REF,Vector_SYM)
COOL_TYPE_DEF(Void       , 51,"Void",Void_T,Void_REF,Void_SYM)
COOL_TYPE_DEF(Actor      , 52,"Actor",Actor_T,Actor_REF,Actor_SYM)
COOL_TYPE_DEF(Arg        , 53,"Arg",Arg_T,Arg_REF,Arg_SYM)
COOL_TYPE_DEF(Field      , 54,"Field",Field_T,Field_REF,Field_SYM)
COOL_TYPE_DEF(Import     , 55,"Import",Import_T,Import_REF,Import_SYM)
COOL_TYPE_DEF(Local      , 56,"Local",Local_T,Local_REF,Local_SYM)
COOL_TYPE_DEF(Package    , 57,"Package",Package_T,Package_REF,Package_SYM)
#undef COOL_TYPE_DEF
